In [33]:
import requests
import pandas as pd
from pathlib import Path
import os

In [36]:
data_path = Path("./ignore/footbal_data_org")
os.makedirs(data_path, exist_ok = True)

base_url = "http://api.football-data.org"

In [37]:
response = requests.get(f"{base_url}/v4/competitions/")
competitions_json = response.json()

   count                                       competitions
0    183  [{'id': 2166, 'area': {'id': 2001, 'name': 'Af...

In [54]:
# type(competitions_json['competitions'])
# competitions_json['competitions']
competitions = pd.json_normalize(competitions_json['competitions'])
competitions

,id,name,code,type,emblem,plan,numberOfAvailableSeasons,lastUpdated,area.id,area.name,...,currentSeason.winner.shortName,currentSeason.winner.tla,currentSeason.winner.crest,currentSeason.winner.address,currentSeason.winner.website,currentSeason.winner.founded,currentSeason.winner.clubColors,currentSeason.winner.venue,currentSeason.winner.lastUpdated,currentSeason
0,2166,AFC Champions League,ACL,CUP,None,TIER_FOUR,1,2023-02-26T12:57:33Z,2001,Africa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006,WC Qualification CAF,QCAF,CUP,None,TIER_FOUR,3,2022-03-13T18:51:44Z,2001,Africa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2176,Africa Cup,AC,CUP,https://crests.football-data.org/ac.png,TIER_FOUR,1,2024-01-13T11:34:43Z,2001,Africa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023,Primera B Nacional,PBN,LEAGUE,None,TIER_FOUR,5,2023-08-01T08:40:24Z,2011,Argentina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,Liga Profesional,ASL,LEAGUE,https://crests.football-data.org/LPDF.svg,TIER_TWO,7,2024-09-13T16:34:03Z,2011,Argentina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,2180,Club Friendlies,CLF,PLAYOFFS,None,TIER_FOUR,1,2024-06-20T19:26:54Z,2267,World,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,2000,FIFA World Cup,WC,CUP,https://crests.football-data.org/qatar.png,TIER_ONE,22,2024-09-13T17:04:20Z,2267,World,...,Argentina,ARG,https://crests.football-data.org/762.png,"Viamonte 1366/76 Buenos Aires, Buenos Aires 1053",http://www.afa.org.ar,1893.0,Sky Blue / White / Black,None,2022-05-17T21:09:25Z,NaN
180,2167,FIFA Women's World Cup,WCF,CUP,https://crests.football-data.org/fwwc.svg,TIER_FOUR,1,2023-04-05T11:47:08Z,2267,World,...,Spain,ESP,https://crests.football-data.org/760.svg,"Ramón y Cajal, s/n Las Rozas 28230",http://www.rfef.es,1909.0,Red / Blue / Yellow,Estadio Nuevo Municipal Las Gaunas,2023-04-05T11:14:25Z,NaN
181,2153,Summer Olympics,OLY,CUP,https://upload.wikimedia.org/wikipedia/commons...,TIER_FOUR,2,2021-07-21T15:39:38Z,2267,World,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,2155,WC Qualification CONCACAF,QCCF,CUP,None,TIER_FOUR,2,2021-11-11T10:39:10Z,2267,World,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
competitions.columns

Index(['id', 'name', 'code', 'type', 'emblem', 'plan',
       'numberOfAvailableSeasons', 'lastUpdated', 'area.id', 'area.name',
       'area.code', 'area.flag', 'currentSeason.id', 'currentSeason.startDate',
       'currentSeason.endDate', 'currentSeason.currentMatchday',
       'currentSeason.winner', 'currentSeason.winner.id',
       'currentSeason.winner.name', 'currentSeason.winner.shortName',
       'currentSeason.winner.tla', 'currentSeason.winner.crest',
       'currentSeason.winner.address', 'currentSeason.winner.website',
       'currentSeason.winner.founded', 'currentSeason.winner.clubColors',
       'currentSeason.winner.venue', 'currentSeason.winner.lastUpdated',
       'currentSeason'],
      dtype='object')

In [35]:
competitions.to_csv(data_path/"competitions.csv")

In [41]:
areas_r = requests.get(f"{base_url}/v4/areas/")
areas_json = areas_r.json()
# areas_json

In [42]:
areas = pd.json_normalize(areas_json["areas"])
areas

       id            name countryCode  flag  parentAreaId parentArea
0    2000     Afghanistan         AFG  None        2014.0       Asia
1    2001          Africa         AFR  None        2267.0      World
2    2002         Albania         ALB  None        2077.0     Europe
3    2004         Algeria         ALG  None        2001.0     Africa
4    2005  American Samoa         ASM  None        2175.0    Oceania
..    ...             ...         ...   ...           ...        ...
267  2268           Yemen         YEM  None        2014.0       Asia
268  2269      Yugoslavia         YUG  None        2077.0     Europe
269  2270          Zambia         ZAM  None        2001.0     Africa
270  2271        Zanzibar         ZAN  None        2001.0     Africa
271  2272        Zimbabwe         ZIM  None        2001.0     Africa

[272 rows x 6 columns]

areas.to_csv(data_path/"areas.json")

In [60]:
# competitions[competitions["area.code"]=='ENG' & competitions.code=="PL"]
competitions[competitions.code=="PL"]
# competitions.columns

,id,name,code,type,emblem,plan,numberOfAvailableSeasons,lastUpdated,area.id,area.name,...,currentSeason.winner.shortName,currentSeason.winner.tla,currentSeason.winner.crest,currentSeason.winner.address,currentSeason.winner.website,currentSeason.winner.founded,currentSeason.winner.clubColors,currentSeason.winner.venue,currentSeason.winner.lastUpdated,currentSeason
48,2021,Premier League,PL,LEAGUE,https://crests.football-data.org/PL.png,TIER_ONE,126,2024-09-13T16:51:24Z,2072,England,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
compettition_pl_resp = requests.get(f"{base_url}/v4/competitions/PL")
compettition_pl_json = compettition_pl_resp.json()
compettition_pl_json

{'message': 'The resource you are looking for is restricted and apparently not within your permissions. Please check your subscription.',
 'errorCode': 403}

In [64]:
ronaldo_resp = requests.get(f"{base_url}/v4/persons/44")
ronaldo_json = ronaldo_resp.json()
ronaldo_json

{'message': 'The resource you are looking for is restricted and apparently not within your permissions. Please check your subscription.',
 'errorCode': 403}